spring.application.name=demo-for-mapStruct


server.port=8081

spring.datasource.url = jdbc:mysql://localhost:3306/mapstructdemo
spring.datasource.username = root
spring.datasource.password = Saireva1*
spring.jpa.hibernate.ddl-auto = update

spring.jpa.show-sql=true
